// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/base.proto

package xGrpcGenerate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Code          uint64                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	Overhead      *int64                 `protobuf:"varint,6,opt,name=overhead,proto3,oneof" json:"overhead,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Error         *GrpcError             `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_base_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *BaseResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *BaseResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *BaseResponse) GetOverhead() int64 {
	if x != nil && x.Overhead != nil {
		return *x.Overhead
	}
	return 0
}

func (x *BaseResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BaseResponse) GetError() *GrpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_base_proto protoreflect.FileDescriptor

const file_proto_base_proto_rawDesc = "" +
	"\n" +
	"\x10proto/base.proto\x12\x05xBase\x1a\x19google/protobuf/any.proto\x1a\x11proto/error.proto\"\xaa\x02\n" +
	"\fBaseResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x04R\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12\x1f\n" +
	"\boverhead\x18\x06 \x01(\x03H\x01R\boverhead\x88\x01\x01\x12(\n" +
	"\x04data\x18\a \x01(\v2\x14.google.protobuf.AnyR\x04data\x12&\n" +
	"\x05error\x18\b \x01(\v2\x10.xBase.GrpcErrorR\x05errorB\x10\n" +
	"\x0e_error_messageB\v\n" +
	"\t_overheadB\x1fZ\x1d./grpc/generate;xGrpcGenerateb\x06proto3"

var (
	file_proto_base_proto_rawDescOnce sync.Once
	file_proto_base_proto_rawDescData []byte
)

func file_proto_base_proto_rawDescGZIP() []byte {
	file_proto_base_proto_rawDescOnce.Do(func() {
		file_proto_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_base_proto_rawDesc), len(file_proto_base_proto_rawDesc)))
	})
	return file_proto_base_proto_rawDescData
}

var file_proto_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_base_proto_goTypes = []any{
	(*BaseResponse)(nil), // 0: xBase.BaseResponse
	(*anypb.Any)(nil),    // 1: google.protobuf.Any
	(*GrpcError)(nil),    // 2: xBase.GrpcError
}
var file_proto_base_proto_depIdxs = []int32{
	1, // 0: xBase.BaseResponse.data:type_name -> google.protobuf.Any
	2, // 1: xBase.BaseResponse.error:type_name -> xBase.GrpcError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_base_proto_init() }
func file_proto_base_proto_init() {
	if File_proto_base_proto != nil {
		return
	}
	file_proto_error_proto_init()
	file_proto_base_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_base_proto_rawDesc), len(file_proto_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_base_proto_goTypes,
		DependencyIndexes: file_proto_base_proto_depIdxs,
		MessageInfos:      file_proto_base_proto_msgTypes,
	}.Build()
	File_proto_base_proto = out.File
	file_proto_base_proto_goTypes = nil
	file_proto_base_proto_depIdxs = nil
}
